<?php

declare(strict_types=1);

namespace App\Domain\ValueObjects;

use Webmozart\Assert\Assert;

/**
 * Database-owned UUID identifier.
 *
 * Wraps primary-key and foreign-key UUIDs generated by PostgreSQL
 * (`gen_random_uuid()`) in our own `catalog.*`, `shopwired.*` and related
 * schemas — including the Supabase-shared `auth.*` schema. Kept separate
 * from {@see Guid} — Guid models external-system IDs that happen to use
 * UUID format (Linnworks stockItemId), whereas Uuid models identifiers we
 * own. The distinction is intentional so the two concepts cannot be
 * transparently substituted at type-check time.
 *
 * Validates UUID format on construction.
 */
final readonly class Uuid
{
    public function __construct(
        public string $value,
    ) {
        Assert::uuid($value, 'Invalid UUID format: %s');
    }

    /**
     * Create from a trusted source.
     *
     * Note: Still validates (constructor runs Assert::uuid). Use when the value
     * is known-good (e.g., from database) and validation cost is acceptable.
     */
    public static function fromTrusted(string $value): self
    {
        return new self($value);
    }

    public function equals(self $other): bool
    {
        return \mb_strtolower($this->value) === \mb_strtolower($other->value);
    }
}
